### ISSUE TITLE
Does mybinder.org supports R 4.2?

### ISSUE THREAD

**Issue by rgaiacs** [binder-examples/r#38]
My `runtime.txt` has

```
r-4.2-2023-03-01
```

and launch https://mybinder.org/v2/gh/GESIS-Methods-Hub/minimal-example-qmd-rstats-xml2/HEAD gives me

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerbwntvooj'...
HEAD is now at d1435a6 Replace xml2 example output
Error during build: Extra data: line 1 column 5 (char 4)
```

**Comment by hluetck** [comment]
This seems to be a general problem with `repo2docker` and `R` repositories. My `runtime.txt` has
```
r-4.1-2022-01-10
```
and running `jupyter-repo2docker r_demo_repo` gives me:
```
Picked Local content provider.
Using local repo r_demo_repo.
Traceback (most recent call last):
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/henry/opt/miniconda3/envs/repo2docker/bin/jupyter-repo2docker", line 10, in <module>
    sys.exit(main())
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/__main__.py", line 422, in main
    r2d.start()
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/app.py", line 841, in start
    self.build()
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/app.py", line 793, in build
    picked_buildpack.render(build_args),
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/base.py", line 458, in render
    for user, script in self.get_build_scripts():
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/r.py", line 278, in get_build_scripts
    cran_mirror_url = self.get_cran_mirror_url(self.checkpoint_date)
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/r.py", line 241, in get_cran_mirror_url
    return self.get_rspm_snapshot_url(snapshot_date)
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/r.py", line 200, in get_rspm_snapshot_url
    snapshots = requests.post(
  File "/Users/henry/opt/miniconda3/envs/repo2docker/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by hluetck** [comment]
It is handled in this issue:
https://github.com/jupyterhub/repo2docker/issues/1272
